services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - USER=${TRANSMISSION_USER:-admin}
      - PASS=${TRANSMISSION_PASS}
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./watch:/watch
    ports:
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  web_tv:
    build: .
    container_name: mult_tv_app
    environment:
      - TRANSMISSION_USER=${TRANSMISSION_USER:-admin}
      - TRANSMISSION_PASS=${TRANSMISSION_PASS}
    ports:
      - 80:8000
    volumes:
      - ./downloads:/downloads
      - ./app:/app/data
    restart: unless-stopped
    depends_on:
      - transmission